"use client";

import Navbar from "@/components/Navbar";
import ReactQueryProvider from "@/components/ReactQueryProvider";
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isTelegramAvailable =
    typeof window !== "undefined" && (window as any).Telegram?.WebApp;

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {isTelegramAvailable && (
          <ThemeProvider attribute={"class"} defaultTheme="system">
            <ReactQueryProvider>
              <Navbar />
              {children}
            </ReactQueryProvider>
          </ThemeProvider>
        )}
      </body>
    </html>
  );
}
